### ISSUE TITLE
Files and folders color

### ISSUE THREAD

**Issue by Guiller02** [AndrewVos/terminal-themer#2]
Hi, awesome project, but is there a way to change the colors of files and folders? 

my pantheon terminal now is look like this:
![Screenshot from 2020-04-09 13-05-03](https://user-images.githubusercontent.com/37823327/78915783-d361b100-7a62-11ea-8be4-848f5f89ab3a.png)

and i wanna use full dracula like this other gnome terminal:
![Screenshot from 2020-04-09 13-07-14](https://user-images.githubusercontent.com/37823327/78915920-0e63e480-7a63-11ea-9e18-943975ac98f5.png)

**Comment by AndrewVos** [comment]
I think that should change too. You probably aren't running ls with the
colour option turned on?

Try
https://superuser.com/questions/665274/how-to-make-ls-color-its-output-by-default-without-setting-up-an-alias

**Comment by Guiller02** [comment]
actually i've quitted elementary os, but thanks for the help

**Comment by AndrewVos** [comment]
No problem buddy
